spring:
  application:
    name: MICRO_CLIENT
  datasource:
    url: jdbc:mysql://localhost:3306/ssmdemo?characterEncoding=utf-8&useUnicode=true&useSSL=true&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.springboot.service.user.pojo
  #  mapper-locations: classpath*:/mapping/**/*Mapper.xml,classpath*:/mapping/**/CommonSQL.xml
  mapper-locations: classpath*:/mapping/**/*Mapper.xml,classpath*:/mapping/sql/CommonSQL.xml
#  mapper-locations: classpath*:/mapping/**/*.xml

swagger:
  basePackage: com.springboot.client.user.controller
  title: springboot title
  description: springboot description
  version: V1.0

server:
  port: 8081
  context-path: /micro_client

eureka:
  instance:
    hostname: 127.0.0.1
    preferIpAddress: true
    health-check-url: http://${eureka.instance.hostname}:${server.port}${server.context-path}/actuator/health
    status-page-url: http://${eureka.instance.hostname}:${server.port}${server.context-path}/actuator/info
    home-page-url: http://${eureka.instance.hostname}:${server.port}${server.context-path}
    metadata-map:
      configPath: ${server.context-path}
      management:
        context-path: ${server.context-path}

  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:6001/eureka
    register-with-eureka: true
    fetch-registry: true
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 2500
feign.compression.request.enabled: true
feign.compression.response.enabled: true
feign.compression.request.min-request-size: 2048
feign.compression.request.mime-types: text/xml,application/xml,application/json
feign.hystrix.enabled: true